### PR TITLE
GSNCA analysis module added 

### PR DESCRIPTION
**Pull request by runjin326**
## Description

This PR adds the GSNCA analysis that compares the top 20 similar patients to patient of interest to GTEx brain normal, PBTA HGG and PBTA all samples to find pathways that are differently networked in two groups.

Fixes # https://github.com/d3b-center/bixu-tracker/issues/1260

Things to note:
1) Currently, the analysis looks at C2 pathways of MsigDB of 10-500 genes in there - but this is subject to change per feedback.
2) The output is uploaded in the `output` folder of module just for results review for the reviewers - however, the code does code to put the files in `output_dir <- file.path(patient_dir, "output", "gsnca_analysis")` 
    - only 2 files are uploaded for demonstration purposes - also note that the files are not ran on all pathways - a total of >2000 pathways were included so to run through them, it would take a couple hours locally ( I believe it already took 2hrs to run on 1k pathways) 
    
3) The text file output files from GSNCA are filtered to contain value < 0.05 and arrange by pvalue - 
- `top20_similar_vs_GTEx_GSNCA_analysis.tsv`
- `top20_similar_vs_PBTA_HGG_GSNCA_analysis.tsv`
- `top20_similar_vs_PBTA_all_GSNCA_analysis.tsv`
4) The plot outputs containing top 5 differentially networked pathways are:
- `top20_similar_vs_PBTA_HGG_GSNCA_plots.pdf`
- `top20_similar_vs_PBTA_all_GSNCA_plots.pdf`
- `top20_similar_vs_GTEx_GSNCA_plots.pdf`
5) To annotate DGE table in drug recommendation - the code `code/drug_recommendations/p10_transcriptome_drug_rec.R` is modified accordingly.

Please check to make sure the output formats are as expected. 

## Type of review for this PR
- [x] Scientific / output review
- [x] Code quality review

note: scientific/output review requires the lead scientists or analysts of the project to be more focus on the output of the PR where code quality review requires reviewer to make sure the PR is following the [contributing guideline](https://www.notion.so/d3b/contributing-721d172616b24ff395a64c18c58534f5) 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I tested locally with data structure in OMPARE and the results turned out to be as expected.

- [ ] Unit test
- [ ] Integration test

**Test Configuration**:
* Environment:
* Test files:

**Task link/Screenshot/Terminal returns**:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have emojis in my PR and commits 😉

### CODE REVIEW

**Review by komalsrathi — APPROVED** [review]
Hi @runjin326. I just made a couple of minor changes and one major change. 

When I was testing this with patient 46, it was failing for GTEx with the following error: `deviation smaller than 'min.sd' in group 1` because for some genes in the PNOC008 similar TPM (i.e. group 1) the SD was < 0.001 which is the `min.sd` requirement by `GSNCAtest`.  Because the PNOC008 similar TPM is not filtered for expression, I added a line to remove all genes with sd < 0.001 in [this commit](https://github.com/runjin326/OMPARE/commit/9d671590cd95d97f83591db163ef7f56af8ae79c). I tested on 46 and it works now. 

Can you please extend these small changes to the generalized report as well to be consistent between the two repos? Thanks so much!!

**Comment by runjin326** [comment]
@komalsrathi, thanks so much for making those changes! Weird I thought there should be a filter step for PNOC008 in place but oh well - I will made corresponding changes in the generalized report.

**Comment by komalsrathi** [comment]
> @komalsrathi, thanks so much for making those changes! Weird I thought there should be a filter step for PNOC008 in place but oh well - I will made corresponding changes in the generalized report.

actually if you think the same expression filter step would make more sense, you can probably add that instead?

**Comment by runjin326** [comment]
@komalsrathi, yes sure - just implemented that.

**Comment by komalsrathi** [comment]
@runjin326 can you pull the latest changes from master? thank you!

**Comment by komalsrathi** [comment]
@aadamk can you review this when you get a chance? I tested it on the latest patient and it worked as expected.

**Review by aadamk — APPROVED** [review]
Code and output all look good to me

**Pull request merged**
