### PR TITLE
Drug synergy update

### PR DESCRIPTION
**Pull request by runjin326**
## Description

This PR improves the run-time of this module from hours to within minutes. 
Basically, instead of calculating the closeness, betweenness and rank for the entire network and each drug for each drug pair, those numbers are pre-calculated and extracted for each combination. 
Since the scores are calculated only once (instead of previously, they are calculated a lot of times) and the calculation is the time-consuming step, the  performance is significantly better. 

One question - I did not do any further filtering for the drugs. I can download the touchstone dataset of compounds that are in CMap class, kinase and enzyme inhibitors (800 compounds) and do further filtering if necessary. That would probably remove 20-30% of the drugs that we currently have. Please advise whether that is still necessary. (@aadamk) 

Fixes # (issue) https://github.com/d3b-center/bixu-tracker/issues/1273

## Type of review for this PR
- [ ] Scientific / output review
- [x] Code quality review

note: scientific/output review requires the lead scientists or analysts of the project to be more focus on the output of the PR where code quality review requires reviewer to make sure the PR is following the [contributing guideline](https://www.notion.so/d3b/contributing-721d172616b24ff395a64c18c58534f5) 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I downloaded the files for PNOC008-41 and ran the module with those samples and the results were generated within a few minutes. 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have emojis in my PR and commits 😉

### CODE REVIEW

**Review by komalsrathi — APPROVED** [review]
Works super fast! thanks @runjin326 !!

**Comment by komalsrathi** [comment]
@aadamk the module runs pretty fast and this is ready to merge. If we still need additional filtering strategies, I will keep this open.

**Comment by aadamk** [comment]
I think for interpretability, it would be valuable to filter to touchstone - though this should be ~3000 compounds according to the connectopedia (https://clue.io/connectopedia/the_touchstone_dataset). @runjin326 - you found 800 cmap, kinase, and enzyme inhibitors; do you know the broad MOA's of the other 2200 drugs as part of touchstone?

**Comment by runjin326** [comment]
@aadamk - I got the info from this website (https://clue.io/touchstone#)
I am attaching the data that I downloaded:
- Full dataset:
[touchstone_all.txt](https://github.com/d3b-center/OMPARE/files/7816200/touchstone_all.txt)
- Filtered dataset:
[touchstone_filtered.txt](https://github.com/d3b-center/OMPARE/files/7816201/touchstone_filtered.txt)
image

And here is the filtered out df:
[filtered_out.txt](https://github.com/d3b-center/OMPARE/files/7816241/filtered_out.txt)
Looks like there are some interesting EGFR inhibitors so maybe we shouldn't filter.

If you prefer, I can just use the 2429 compounds from the first attached file and do a filtering of the drugs before doing the calculation.

**Review by aadamk — APPROVED** [review]
@runjin326 confirmed that the synergy results are identical for patient 41 from 008. 

For the touchstone dataset, I'll actually hold off and review the 2021 LINCS data release from the Maayan lab first. 

Looks ready to merge - thanks!

**Pull request merged**
